### ISSUE TITLE
npmplus will not load - "Startup Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node" flooding logs

### ISSUE THREAD

**Issue by Drakonas** [ZoeyVid/NPMplus#2352]
NPMplus will not load after pulling an update, and the log is filled with these errors. I'm not sure what's going on here. I just updated to the latest develop image as of 10 minutes of writing this post. Thoughts?

```
[Global   ] › ✖  error     Startup Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found
    at Object..node (node:internal/modules/cjs/loader:1921:18)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[Global   ] › ✖  error     Startup Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found
    at Object..node (node:internal/modules/cjs/loader:1921:18)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[Global   ] › ✖  error     Startup Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found
    at Object..node (node:internal/modules/cjs/loader:1921:18)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[Global   ] › ✖  error     Startup Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found
    at Object..node (node:internal/modules/cjs/loader:1921:18)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[Global   ] › ✖  error     Startup Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found
    at Object..node (node:internal/modules/cjs/loader:1921:18)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[Global   ] › ✖  error     Startup Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found
    at Object..node (node:internal/modules/cjs/loader:1921:18)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[Global   ] › ✖  error     Startup Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found
    at Object..node (node:internal/modules/cjs/loader:1921:18)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12) {
  code: 'ERR_DLOPEN_FAILED'
}
[Global   ] › ✖  error     Startup Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found Error: Error relocating /app/node_modules/better-sqlite3/build/Release/better_sqlite3.node: _ZN2v86Object14GetPrototypeV2Ev: symbol not found
    at Object..node (node:internal/modules/cjs/loader:1921:18)
    at Module.load (node:internal/modules/cjs/loader:1465:32)
    at Function._load (node:internal/modules/cjs/loader:1282:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Module.require (node:internal/modules/cjs/loader:1487:12)
    at require (node:internal/modules/helpers:135:16)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at new Database (/app/node_modules/better-sqlite3/lib/database.js:48:64)
    at Client_BetterSQLite3.acquireRawConnection (/app/node_modules/knex/lib/dialects/better-sqlite3/index.js:14:12) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by Zoey2936** [comment]
your compose.yaml?

**Comment by Zoey2936** [comment]
Can confirm, give me 30 minutes

**Comment by Zoey2936** [comment]
fixed

**Comment by Drakonas** [comment]
Apologies @Zoey2936 I went to bed. Thanks!

**Comment by rursache** [comment]
still broken as of this second using the `develop` tag via docker. had to downgrade to `pr-2346` which works

**Comment by Drakonas** [comment]
> still broken as of this second using the `develop` tag via docker. had to downgrade to `pr-2346` which works

Gotcha. That must explain #2356 that I made.
