### ISSUE TITLE
NPMplus not working after recent update

### ISSUE THREAD

**Issue by Joly0** [ZoeyVid/NPMplus#698]
Hey, i just noticed, that i cant access my domains anymore. Was curious what happened and couldnt reach the npmplus page aswell. I tried to restart the npmplus container, it starts, but doesnt do anything afterwards:

```
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.19/community/x86_64/APKINDEX.tar.gz
OK: 94 MiB in 91 packages
----------------------------------------------------------
Let's Encrypt certificates cleanup - 2024/03/12 13:16:25
----------------------------------------------------------
Keeping /data/tls/certbot/archive/npm-10/cert4.pem.
Keeping /data/tls/certbot/archive/npm-10/chain4.pem.
Keeping /data/tls/certbot/archive/npm-10/fullchain4.pem.
Keeping /data/tls/certbot/archive/npm-10/privkey4.pem.
Keeping /data/tls/certbot/archive/npm-13/cert1.pem.
Keeping /data/tls/certbot/archive/npm-13/chain1.pem.
Keeping /data/tls/certbot/archive/npm-13/fullchain1.pem.
Keeping /data/tls/certbot/archive/npm-13/privkey1.pem.
8 file(s) kept.
0 file(s) deleted.
'/usr/local/nginx/conf/conf.d/include/coreruleset/plugins/README.md' -> '/data/etc/modsecurity/crs-plugins/README.md'
'/usr/local/nginx/conf/conf.d/include/coreruleset/plugins/empty-after.conf' -> '/data/etc/modsecurity/crs-plugins/empty-after.conf'
'/usr/local/nginx/conf/conf.d/include/coreruleset/plugins/empty-before.conf' -> '/data/etc/modsecurity/crs-plugins/empty-before.conf'
'/usr/local/nginx/conf/conf.d/include/coreruleset/plugins/empty-config.conf' -> '/data/etc/modsecurity/crs-plugins/empty-config.conf'
no DEFAULT_CERT_ID set, using dummycerts.
Working on file: /data/nginx/custom/events.conf
Working on file: /data/nginx/custom/http.conf
Working on file: /data/nginx/custom/http_top.conf
Working on file: /data/nginx/custom/root.conf
Working on file: /data/nginx/custom/server_dead.conf
Working on file: /data/nginx/custom/server_proxy.conf
Working on file: /data/nginx/custom/server_redirect.conf
Working on file: /data/nginx/custom/server_stream.conf
Working on file: /data/nginx/custom/server_stream_tcp.conf
Working on file: /data/nginx/custom/server_stream_udp.conf
Working on file: /data/nginx/custom/stream.conf
Working on file: /data/nginx/custom/stream_top.conf
Working on file: /data/nginx/default.conf
Working on file: /data/nginx/ip_ranges.conf
Working on file: /data/nginx/proxy_host/1.conf
Working on file: /data/nginx/proxy_host/11.conf
Working on file: /data/nginx/proxy_host/12.conf
Working on file: /data/nginx/proxy_host/2.conf
Working on file: /data/nginx/proxy_host/3.conf
Working on file: /data/nginx/proxy_host/5.conf
Working on file: /data/nginx/proxy_host/8.conf
Success.
usermod: no changes

-------------------------------------
 _ _  ___  __ __       _
| \ || . \|  \  \ ___ | | _ _  ___
|   ||  _/|     || . \| || | |[_-[
|_\_||_|  |_|_|_||  _/|_| \__|/__/
                 |_|
-------------------------------------
Version:  2.11.1+9d0574e
Date:     Tue Mar 12 13:16:26 CET 2024
User:     npm
PUID:     99
User ID:  99
PGID:     100
Group ID: 100
-------------------------------------
```

**Comment by Joly0** [comment]
All my domains report this now:
![grafik](https://github.com/ZoeyVid/NPMplus/assets/13993216/5fc6c578-a6de-41b8-8942-1847d2faedb4)

**Comment by Joly0** [comment]
And i can confirm it works again when changing from latest tag to 389

**Comment by ExXxtr3me** [comment]
Just updated to the newest version from docker hub (391) but it's still not working:
![image](https://github.com/ZoeyVid/NPMplus/assets/6366829/dba8ba82-ebc8-43a0-9828-531a1c9b77bd)

**Comment by scampower3** [comment]
Yes, same. Still not working.

**Comment by Zoey2936** [comment]
should be fixed now

**Comment by Joly0** [comment]
I just pulled from latest, and somehow its still not working?

**Comment by Zoey2936** [comment]
can you please send your logs?

**Comment by Joly0** [comment]
nvm, somethign was bugged and it didnt pull latest, although i added the latest tag. removed the image and pulled again, now its working
